### ISSUE TITLE
Admin login still not working

### ISSUE THREAD

**Issue by jusulli** [lleague/university_of_michigan_stewart_wang_site#1]
The admin login is still not working.  All users see the initial login screen but receive this error when attempting to log in.
[Action Controller_ Exception caught.pdf](https://github.com/lleague/university_of_michigan_stewart_wang_site/files/1568735/Action.Controller_.Exception.caught.pdf)

**Comment by lleague** [comment]
Chrome blocks the authenticity token on some secure networks. It'll work in Safari or Firefox.
